pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_USER = "akifmhd"
        IMAGE_NAME = "frontend:1.0"
        FULL_IMAGE = "${DOCKER_USER}/${IMAGE_NAME}"
        TRIVY_CACHE_DIR = "${WORKSPACE}/.trivy-cache"
        REPORTS_DIR = "${WORKSPACE}/reports"

    }
    
    stages{
        stage('cleanigng workspace'){
            steps{
                cleanWs()
            }
        }
        stage('cloning repo'){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/x091204/three-tier-snake-game.git'
            }
        }

        stage('sonarqube analysis'){
            steps{
            dir('frontend'){
                withSonarQubeEnv('sonar-server') {
                    sh """
                    ${SCANNER_HOME}/bin/sonar-scanner \
                    -Dsonar.projectName=three-tier-frontend \
                    -Dsonar.projectKey=three-tier-frontend \
                    -Dsonar.sources=. \
                    """
                }
                }
            }
        }
        stage('building docker image'){
            steps{
                dir('frontend'){
                sh "docker build -t ${FULL_IMAGE} ."
                }
            }
        }
        stage('trivy scan'){
            steps{
                sh "mkdir -p ${TRIVY_CACHE_DIR} ${REPORTS_DIR} trivy"
                sh "wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O trivy/html.tpl"
                sh """
                trivy image \
                --cache-dir ${TRIVY_CACHE_DIR} \
                --severity HIGH,CRITICAL \
                --ignore-unfixed \
                --scanners vuln \
                --format template \
                --template "@trivy/html.tpl" \
                --output ${REPORTS_DIR}/trivy-report.html \
                --exit-code 1 \
                ${FULL_IMAGE} \ """
            }
        }
    }
      
}