pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_USER = "akifmhd"
        IMAGE_NAME = "frontend:1.0"
        FULL_IMAGE = "${DOCKER_USER}/${IMAGE_NAME}"

    }
    
    stages{
        stage('cleanigng workspace'){
            steps{
                cleanWs()
            }
        }
        stage('cloning repo'){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/x091204/three-tier-snake-game.git'
            }
        }

        stage('sonarqube analysis'){
            steps{
            dir('frontend'){
                withSonarQubeEnv('sonar-server') {
                    sh """
                    ${SCANNER_HOME}/bin/sonar-scanner \
                    -Dsonar.projectName=three-tier-frontend \
                    -Dsonar.projectKey=three-tier-frontend \
                    -Dsonar.sources=. \
                    """
                }
                }
            }
        }
    }
      
}