apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - three-tier-dev
  selector:
    matchLabels:
      app: backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
