services:

  database:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_database:/data/db
    networks:
      - three-tier
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  backend:
    container_name: backend
    image: akifmhd/backend:1.0.1
    ports:
      - "5000:5000"
    networks:
      - three-tier
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env.docker
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: akifmhd/frontend:1.0.1
    ports:
      - "8080:80"
    networks:
      - three-tier
    depends_on:
      - backend
    restart: unless-stopped
  
  auth-service:
    container_name: auth-service
    image: akifmhd/auth-service:1.0
    ports:
      - "4000:4000"
    networks:
      - three-tier
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./auth-service/.env.docker
    restart: unless-stopped

volumes:
  mongo_database:
networks:
  three-tier:
