apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - three-tier-dev
  selector:
    matchLabels:
      app: auth

  endpoints:
    - port: http
      path: /metrics
      interval: 15s