apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: auth
  namespaceSelector:
    matchNames:
      - three-tier-dev
  endpoints:
  - port: http
    path: /metrics
    interval: 15s