apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - name: backend-svc
    protocol: TCP
    port: 5000
    targetPort: 5000