apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicasCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: 80
        readinessProbe: 
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10 
          periodSeconds: 5 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false