apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017
    targetPort: 27017