apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-sec
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWUwMQ==
  mongo-root-password: cGFzc3dvcmQwMQ==