pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_USER = "akifmhd"
        IMAGE_NAME = "auth-service:1.0"
        FULL_IMAGE = "${DOCKER_USER}/${IMAGE_NAME}"
        TRIVY_CACHE_DIR = "${WORKSPACE}/.trivy-cache"
        REPORTS_DIR = "${WORKSPACE}/reports"
    }

    stages{
        stage('cleaning workspace'){
            steps{
                cleanWs()
            }
        }
        stage('cloning repo'){
            steps{
                git branch: 'new-model', changelog: false, poll: false, url: 'https://github.com/x091204/three-tier-snake-game.git'
            }
        }
        stage('sonarqube analysis'){
            steps{
                dir('auth-service'){
                    withSonarQubeEnv('sonar-server'){
                        sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectName=three-tier-auth-service \
                        -Dsonar.projectKey=three-tier-auth-service \
                        -Dsonar.sources=. 
                        """
                    }
                }
            }
        }
        stage('building docker image'){
            steps{
                dir('auth-service'){
                    sh "docker build -t ${FULL_IMAGE} ."
                }
            }
        }
        stage('trivy scan'){
            steps{
                dir('auth-service'){
                    sh "mkdir -p ${TRIVY_CACHE_DIR} ${REPORTS_DIR} trivy"
                    sh "wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O trivy/html.tpl"
            
                    sh """
                    trivy image \
                    --cache-dir ${TRIVY_CACHE_DIR} \
                    --severity HIGH,CRITICAL \
                    --ignore-unfixed \
                    --ignorefile .trivyignore \
                    --scanners vuln \
                    --format template \
                    --template "@trivy/html.tpl" \
                    --output ${REPORTS_DIR}/trivy-report.html \
                    --exit-code 0 \
                    ${FULL_IMAGE}
                    """

                    sh """
                    trivy image \
                    --cache-dir ${TRIVY_CACHE_DIR} \
                    --severity HIGH,CRITICAL \
                    --ignore-unfixed \
                    --ignorefile .trivyignore \
                    --scanners vuln \
                    --exit-code 1 \
                    ${FULL_IMAGE}
                    """
                    }
                }
            }
        stage('pushing docker image'){
            steps{
            withCredentials([usernamePassword(
                credentialsId: 'docker', 
                passwordVariable: 'password', 
                usernameVariable: 'username'
                )]) {
                sh """
                echo $password | docker login -u $username --password-stdin
                docker push ${FULL_IMAGE}
                """
                }
            }
        }
    }
    post {
        always {
        sh "ls -la ${REPORTS_DIR}/"
        archiveArtifacts artifacts: 'reports/*', allowEmptyArchive: true
        cleanWs( patterns: [[pattern: '.trivy_cache/**', type: 'EXCLUDE']])
        sh """
                docker image prune -f
                docker images ${IMAGE_NAME} --format "{{.Tag}}" | sort -r | tail -n +4 | xargs -I {} docker rmi ${IMAGE_NAME}:{} || true
            """
        }
    }
}