pipeline {
    agent any

    environment {
        ECR_REGISTRY = ""
        AWS_REGION = "ap-south-1"
        SCANNER_HOME = tool 'sonar-scanner'
        IMAGE_NAME = "backend"
        IMAGE_TAG  = "1.0.${BUILD_NUMBER}"
        FULL_IMAGE = "${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
        TRIVY_CACHE_DIR = "${WORKSPACE}/.trivy-cache"
        REPORTS_DIR = "${WORKSPACE}/reports"

    }
    parameters {
    string(name: 'BRANCH', defaultValue: 'main', description: 'Branch to build')
    }
    
    stages{
        stage('cleaning workspace'){
            steps{
                cleanWs()
            }
        }
        stage('cloning repo'){
            steps{
                git branch: "${params.BRANCH}", changelog: false, poll: false, url: 'https://github.com/x091204/three-tier-snake-game.git'
            }
        }

        stage('sonarqube analysis'){
            steps{
            dir('backend'){
                withSonarQubeEnv('sonar-server') {
                    sh """
                    ${SCANNER_HOME}/bin/sonar-scanner \
                    -Dsonar.projectName=three-tier-backend \
                    -Dsonar.projectKey=three-tier-backend \
                    -Dsonar.sources=. 
                    """
                }
                }
            }
        }
        stage('code quality analysis') {
	        steps{
		        script{
		            waitForQualityGate abortPipeline: false, credentialsId: 'sonarqube'
		        }
	        }
        }
        stage('building docker image'){
            steps{
                dir('backend'){
                sh "docker build -t ${FULL_IMAGE} ."
                }
            }
        }
        stage('trivy scan'){
            steps{
                dir('backend'){
                sh "mkdir -p ${TRIVY_CACHE_DIR} ${REPORTS_DIR} trivy"
                sh "wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O trivy/html.tpl"
                sh """
                trivy image \
                --cache-dir ${TRIVY_CACHE_DIR} \
                --severity HIGH,CRITICAL \
                --ignore-unfixed \
                --ignorefile .trivyignore \
                --scanners vuln \
                --format template \
                --template "@trivy/html.tpl" \
                --output ${REPORTS_DIR}/trivy-report.html \
                --exit-code 0 \
                ${FULL_IMAGE} """

                sh """
                trivy image \
                --cache-dir ${TRIVY_CACHE_DIR} \
                --severity HIGH,CRITICAL \
                --ignore-unfixed \
                --ignorefile .trivyignore \
                --scanners vuln \
                --exit-code 1 \
                ${FULL_IMAGE}
                """
                }
            }
        }
        tage('pushing to ECR'){
            steps{
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin ${ECR_REGISTRY}

                docker push ${FULL_IMAGE}
                """
                }
        }
    }
    post {
        always {
        sh "ls -la ${REPORTS_DIR}/"
        archiveArtifacts artifacts: 'reports/*', allowEmptyArchive: true
        cleanWs( patterns: [[pattern: '.trivy-cache/**', type: 'EXCLUDE']])
        sh """
                docker image prune -f
                docker images ${IMAGE_NAME} --format "{{.Tag}}" | sort -r | tail -n +4 | xargs -I {} docker rmi ${IMAGE_NAME}:{} || true
            """
        }
    }
}