namespace: three-tier-dev

frontend:
  image: akifmhd/frontend
  tag: "1.1"
  replicasCount: 1

backend:
  image: akifmhd/backend
  tag: "1.0"
  replicasCount: 1

mongodb:
  image: mongo
  tag: "7.0"
  replicasCount: 1
