namespace: three-tier-dev

frontend:
  image: <AWS_AC_ID>.dkr.ecr.ap-south-1.amazonaws.com/frontend
  tag: "1.0.3"
  replicasCount: 1

backend:
  image: <AWS_AC_ID>.dkr.ecr.ap-south-1.amazonaws.com/backend
  tag: "1.0.4"
  replicasCount: 1

mongodb:
  image: mongo
  tag: "7.0"
  replicasCount: 1
  storageSize: "100Mi"
  storageClassName: "gp2"

auth:
  image: <AWS_AC_ID>.dkr.ecr.ap-south-1.amazonaws.com/auth-service
  tag: "1.0.3"
  replicasCount: 1
