apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: three-tier-dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: backend
        image: akifmhd/backend:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10 ##Wait 10 seconds after the container starts before Kubernetes runs the first health check.
          periodSeconds: 5 
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: 250Mi
            cpu: 500m
          requests:
            memory: 250Mi
            cpu: 300m
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false

