apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
  namespace: three-tier-dev
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: auth-service
        image: akifmhd/auth-service:1.0
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: auth-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: 250Mi
            cpu: 500m
          requests:
            memory: 250Mi
            cpu: 300m
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false