apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: three-tier-dev
spec:
  rules:
  - host: snake-game.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80