apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: three-tier-dev

resources:
  - namespace.yaml
  - database/mongo-secret.yml
  - database/mongodb-dep.yml
  - database/mongo-svc.yml
  - backend/backend-configmap.yml
  - backend/backend-dep.yml
  - backend/backend-svc.yml
  - auth-service/auth-configmap.yml
  - auth-service/auth-dep.yml
  - auth-service/auth-svc.yml
  - frontend/frontend-dep.yml
  - frontend/frontend-svc.yml
  - monitoring/auth-servicemonitor.yml
  - monitoring/backend-servicemonitor.yml
  - monitoring/grafana-dashboard.yml
  - ingress.yml